# Generated by Django 3.2.11 on 2022-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgs',
            field=models.ImageField(blank=b'I01\n', upload_to='appImage'),
        ),
    ]
