# Generated by Django 3.2.11 on 2022-01-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgs',
            new_name='image',
        ),
    ]
