# Generated by Django 3.2.11 on 2022-01-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
