# Generated by Django 3.2.11 on 2022-01-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='headGov',
        ),
    ]
